# Generated by Django 3.2.3 on 2021-05-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyvalue', '0002_timeuuid_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeuuid',
            name='text',
        ),
    ]
